### ISSUE TITLE
ci: Version of cabal-install installed by setup-haskell should be specified precisely

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#10175]
At the moment the `latest` version of `cabal-install` is installed for validate jobs.

```
       - name: Install primary compiler                                               
         uses: haskell-actions/setup@v2                                          
         id: setup-haskell                                                       
         with:                                                                   
           ghc-version: ${{ env.GHC_FOR_RELEASE }}                               
           cabal-version: latest 
```

This had the effect of completely breaking CI when the definition of "latest" changed. It would be better to explicitly pin a specific version of cabal-install here and update it in a controlled manner.

See #10172
