### ISSUE TITLE
Test suites cannot share a name with their source files

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#1311]
`detailed-0.9` test suites fail to build if the name of the test suite is the same as the name of the exported module. This is all the more serious on systems with case-insensitive filesystems. Minimal example, from the Cabal test suite:

`BuildTestSuiteDetailedV09.cabal`:

```
name: BuildTestSuiteDetailedV09
version: 0.1
license: BSD3
author: Thomas Tuegel
stability: stable
category: PackageTests
build-type: Simple

description:
    Check that Cabal can build test suites of type detailed-0.9.

Library
    exposed-modules: Dummy
    build-depends: base, Cabal

test-suite Dummy
  type:       detailed-0.9
  test-module: Dummy
  build-depends: base, Cabal
```

`Dummy.hs`:

```
module Dummy where

import Distribution.TestSuite (Test)

tests :: IO [Test]
tests = return []
```

A workaround is to rename the test suite. I did this for the case in Cabal's test suite because it wasn't designed to detect this bug, and we need to find out if this bug affects other component types.

See also: #1297 #1310
