### ISSUE TITLE
Cabal format duplicates dependencies

### ISSUE THREAD

**Issue by tfausak** [haskell/cabal#2353]
Running `cabal format` duplicates the `build-depends` section and duplicates dependencies in that section. For example, with this Cabal file:

```
name: example
version: 0
cabal-version: >=1.22.0.0
build-type: Simple
license: MIT
license-file: LICENSE.txt
maintainer: Taylor Fausak <taylor@fausak.me>
synopsis: TODO
description:
    TODO
category: Other

library
    build-depends:
        base ==4.*
    default-language: Haskell2010
```

Repeatedly running `cabal format` produces this:

```
    build-depends:
        base ==4.*
    build-depends:
        base ==4.*
```

```
    build-depends:
        base ==4.*,
        base ==4.*
    build-depends:
        base ==4.*,
        base ==4.*
```

```
    build-depends:
        base ==4.*,
        base ==4.*,
        base ==4.*,
        base ==4.*
    build-depends:
        base ==4.*,
        base ==4.*,
        base ==4.*,
        base ==4.*
```

I would expect `cabal format` to not make any changes to the given Cabal file. I'm using GHC version 7.8.3 and Cabal version 1.22.0.0.
