### ISSUE TITLE
hackage-security cannot gracefully handle absence of package cache directory for file-based remote repositories

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#4136]
Steps to reproduce:

1. In a directory, create `.cabal/config` file with the following contents:

```
repository foo-bar
    url: file:/home/ezyang/Dev/labs/localrepo/repo/
    secure: True
    root-keys:
    key-threshold: 0

remote-repo-cache: /home/ezyang/Dev/labs/raclette/.cabal/packages
```

But you'll need to adjust the two absolute paths to point to a local repository initialized using `hackage-repo-tool` and the `.cabal/packages` directory from your current working directory.

Then run `HOME=$PWD cabal update` and it will fail with:

```
cabal:
/home/ezyang/Dev/labs/raclette/.cabal/packages/foo-bar/hackage-security-lock:
does not exist
```
