### ISSUE TITLE
Support bare wildcard constraints

### ISSUE THREAD

**Issue by tfausak** [haskell/cabal#4802]
Cabal has long had a syntax for wildcard constraints: `foo ==1.*` desugars into `foo >=1 && <2`. I was surprised to discover (via https://github.com/sol/hpack/issues/201) that bare wildcards are not supported: `foo ==*` is a parse error. I would expect it to be the same as `>=0` (or `-any`). Is this something that could be added to Cabal?

**Comment by ivan-m** [comment]
What's the point of using `foo ==*` as opposed to just `foo`?

**Comment by tfausak** [comment]
Convenience. hpack will soon allow you to specify dependencies as a YAML hash. It will also prefix constraints with `==` if they don't already look like constraints. So your dependencies might look like this:

``` yaml
foo: 1.2.3 # foo ==1.2.3
bar: 2.3.* # bar ==2.3.*
```

If you want to specify a dependency without any constraints, there are a few ways to do it but they're all a little weird.

``` yaml
foo: -any # foo -any
bar: '>= 0' # bar >=0 # must be quoted
baz: null # baz -any
qux: # qux -any # implicit null
oof: '*' # oof -any # proposed # also must be quoted
```

Also it makes Cabal's syntax more similar to [npm's SemVer ranges](https://github.com/npm/npm/blob/d081cc6c8d73f2aa698aab36605377c95e916224/doc/misc/semver.md#x-ranges-12x-1x-12-). And I think that it just makes sense: the `*` means "I don't care what this version component is". So why can you say `1.2.*` and `1.*` but not `*`?
