### ISSUE TITLE
`cabal new-test` fails where `stack test` does not

### ISSUE THREAD

**Issue by vaibhavsagar** [haskell/cabal#5583]
I'm trying to track down [an increasingly bizarre bug](https://github.com/kadena-io/pact/pull/195#issuecomment-421384808) and am beginning to wonder if this is a bug in Cabal. Here is a reproduction (that I'm currently working on making smaller):

```bash
$ git clone --recursive -b minimal-failure-repro https://github.com/vaibhavsagar/pact.git
$ cd pact
$ cabal new-test
```

Some observations that may or may not be relevant:

1. The 'hashes' appear to be random snippets from memory.

2. Removing the test that hashes the empty string twice and compares the results causes the other tests to pass.

3. Removing `wreq` from the dependencies in the test-suite causes the tests to pass.

3. Not using `runIO` in the tests, having only one file in the directory instead of two, and duplicating the same file instead of having two different tests also all cause the tests to pass.

I'm experiencing this with GHC 8.2.2 and `cabal-install` 2.0.0.1.

Any advice or suggestions appreciated!

**Comment by phadej** [comment]
Cannot reproduce with `cabal-install-head` (relatively recent)`, GHC-8.2.2 on Ubuntu 18.04 (x86_64).

@vaibhavsagar can you try more recent `cabal-install`. `new-test` in 2.0 is probably broken in very many ways. Which operating system / environment you experience the problem?

**Comment by quasicomputational** [comment]
I can't reproduce either: some dependencies don't build on GHC 8.4.3, and then GHC 8.2.2 is suffering from shadowed dependencies.

Can the example be cut down any?

**Comment by vaibhavsagar** [comment]
Sure, I'm still working on getting it smaller. If you have Nix installed, you can enter a `nix-shell` and run the commands from there.

**Comment by quasicomputational** [comment]
Trying again with an isolated store, it built and tested fine with GHC 8.2.2 and cabal-install 2.4.0.0.

**Comment by vaibhavsagar** [comment]
Fair enough, let me make this failure smaller and easier to reproduce.

**Comment by vaibhavsagar** [comment]
Can you try with revision `1d2320d`? This is failing with cabal-install 2.2.0.0 for me. I will try with a newer cabal-install as well.

**Comment by quasicomputational** [comment]
That commit reproduces for me with GHC 8.2.2 and cabal-install 2.4.0.0. I am just going to verify that it works with stack as well if I use the exact same versions of everything: there's a chance that what you're seeing is that cabal-install is picking a buggy version of some dependency, but the snapshot you're using has a non-buggy version. That's the acid test of whether this is a bug in cabal-install or somewhere else.

**Comment by vaibhavsagar** [comment]
Sure, here's the `stack.yaml`:

```yaml
# stack yaml for ghc builds

resolver: lts-8.15

packages:
  - '.'

extra-deps:
  - bound-2
  - compactable-0.1.2.2
  - ed25519-donna-0.1.1
  - megaparsec-6.5.0
  - parser-combinators-1.0.0
  - algebraic-graphs-0.1.1.1
  - git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
  - git: https://github.com/LeventErkok/sbv.git
    commit: 3dc60340634c82f39f6c5dca2b3859d10925cfdf # with exposed registerKind
```
