### ISSUE TITLE
Difference between `cabal build` and `cabal new-build` on ghc-8.6.3

### ISSUE THREAD

**Issue by tonyday567** [haskell/cabal#5787]
See https://github.com/tidalcycles/Tidal/pull/424 & https://travis-ci.org/tidalcycles/Tidal/builds/465873396

I ran `cabal new-build` and `cabal build` with different results, as part of a travis run.  This is only true for ghc-8.6.3: there was no difference for other versions.

**Comment by gbaz** [comment]
The successful build seems to build `tidal` but not `tidal-vis`. The unsuccessful one appears to try to build `tidal-vis` as well, which is why it even runs into issues with cairo?

Also, and perhaps more to the point, the unsuccessful build appears to be working with cabal 2.0 and ghc 7.10.3, both of which are probably not what you want! https://travis-ci.org/tidalcycles/Tidal/jobs/465873403#L520

**Comment by hvr** [comment]
@tonyday567 also noteworthy: if you use the `language: haskell` travis templates, you don't need to add my PPA explicitly -- Travis CI already uses my PPA -- but with a undocumented quirk: they default to installing the `cabal-install-2.0` package!

Instead with `language: haskell` you should control the `cabal` and `ghc` version via something like

```yaml
language: haskell
dist: trusty

cabal: "2.4"

matrix:
  include:
    - ghc: "8.6.3"  
    - ghc: "8.4.4"
    - ghc: "8.2.2"
    - ghc: "8.0.2"
    - ghc: "7.10.3"
    - ghc: "7.8.4"
    - ghc: "7.6.3"
    - ghc: "7.4.2"
    - ghc: "7.0.4"

install:
 - cabal --version
 - ghc --version

script:
 - cabal v2-update
 - cabal v2-build
 - cabal v2-test --enable-test
```
