### ISSUE TITLE
Human-friendly ghc option names

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/cabal#6071]
It would be nice to be able to write something like

```
ghc-options:
  threaded-runtime: true
  warnings: all
  runtime-options:
    hec: N
    parallel-gc-hecs: 2
    nursery-size: 64m
```

instead of the usual

```
ghc-options:
  -threaded -Wall -with-rtsopts=-N -A64m -qn2
```
