### ISSUE TITLE
Feature: add "default-extensions:" support to global .cabal/config

### ISSUE THREAD

**Issue by mouse07410** [haskell/cabal#6887]
**Describe the bug**
If there is a set of GHC extensions that I regularly use, there seems to be no way to have Cabal apply them automatically. 

Instead, I have to add them manually to each and every project I work with.

**Expected/desired behavior**

Just like I can put in `~/.cabal/config` these:
```yaml
shared: True
. . . . .
extra-include-dirs: my/dir/one,/my/dir/2
. . . . .
```
I'd like to be able to add
```yaml
. . . . .
default-extensions:  ForeignFunctionInterface,GADTs
. . . . .
```
to have those applied to each and every project.

**System information**

Irrelevant.
