### ISSUE TITLE
`cabal check` error location not propagated ("unexpected SecArgName")

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7846]
The syntax error
```
  if (base < 4.7)
    build-depends:
      errorcall-eq-instance  == 0.3.*
```
is reported by `cabal check` as follows:
```
Warning: MissingH.cabal:1:1:
unexpected SecArgName (Position 204 7) "base"
Errors encountered when parsing cabal file ./MissingH.cabal:

MissingH.cabal:1:1: error:
unexpected SecArgName (Position 204 7) "base"

    1 | cabal-version: 1.12
      | ^
Error: cabal: parse error
```

Expected behavior:
- Report error at 204:7 not at 1:1
- User-friendly error message

**Comment by philderbeast** [comment]
I've got another example of this I encountered when I mistyped `impl(ghc-version?)` instead of `impl(ghc?)`.

```yaml
cabal-version: 1.12

name: oh-no
version: 0.1.0
build-type: Simple

library
  hs-source-dirs: src
  if impl(ghc-version > 9.2)
     hs-source-dirs: src-ghc-9.2
  default-language: Haskell2010
```

Gives a reported error of:

```
Warning: oh-no.cabal:1:1:
"<fromParsec'>" (line 1, column 4):
unexpected '-'
expecting end of input
Errors encountered when parsing cabal file ./oh-no.cabal:

oh-no.cabal:1:1: error:
"<fromParsec'>" (line 1, column 4):
unexpected '-'
expecting end of input

    1 | cabal-version: 1.12
      | ^
cabal: parse error
```

At one point I was able to see `unexpected SecArgName` reported but I can't reproduce that again. Here's that error anyway:

```
Warning: oh-no.cabal:1:1:
unexpected SecArgName (Position 23 16) "ghc-version"
Errors encountered when parsing cabal file ./oh-no.cabal:

oh-no.cabal:1:1: error:
unexpected SecArgName (Position 23 16) "ghc-version"

    1 | cabal-version: 2.0
      | ^
cabal: parse error
```
